name: Target Publish New Package

on:
  repository_dispatch:
    types: ["publish_new_android_package"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.REPO_PAT }}

      - name: Add Submodule
        run: git submodule add https://${{ secrets.REPO_PAT }}@github.com/gocanvas/android_sdk.git android_sdk

      - name: Navigate to Submodule and Checkout Branch
        working-directory: android_sdk
        run: |
          LATEST_TAG=$(git tag -l 'release/*' | sort -Vr | head -n 1)
          git checkout $LATEST_TAG

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Access LOCAL_PROPERTIES
        working-directory: android_sdk
        run: echo "${{ secrets.GOCANVAS_LOCAL_PROPERTIES }}" >> ./local.properties

      - name: Grant execute permission for gradlew
        working-directory: android_sdk
        run: chmod +x gradlew

      - name: Publish new package
        working-directory: android_sdk
        run: ./gradlew publishSdkReleasePublicationToGitHubPackagesRepository

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
